# Default values for minecraft-spigot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

image:
  repository: quay.io/kamaradcoal/minecraft-spigot
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.16.5-latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

extraEnv:
  - name: JAR_ARGS
    value: -Xmx1G -Xms512M

kamarad:
  serverId: "1"

spigot:
  config: |
    #Minecraft server properties
    #Wed Oct 06 10:53:01 EEST 2021
    enable-jmx-monitoring=false
    rcon.port=25575
    enable-command-block=false
    gamemode=survival
    enable-query=true
    level-name=world
    motd=A Minecraft Server
    query.port=25565
    pvp=true
    difficulty=easy
    network-compression-threshold=256
    max-tick-time=60000
    require-resource-pack=false
    max-players=20
    use-native-transport=true
    online-mode=false
    enable-status=true
    allow-flight=false
    broadcast-rcon-to-ops=true
    view-distance=10
    server-ip=
    resource-pack-prompt=
    allow-nether=true
    server-port=25565
    enable-rcon=false
    sync-chunk-writes=true
    op-permission-level=4
    prevent-proxy-connections=false
    resource-pack=
    entity-broadcast-range-percentage=100
    rcon.password=
    player-idle-timeout=0
    debug=false
    force-gamemode=false
    rate-limit=0
    hardcore=false
    white-list=false
    broadcast-console-to-ops=true
    spawn-npcs=true
    spawn-animals=true
    snooper-enabled=true
    function-permission-level=2
    text-filtering-config=
    spawn-monsters=true
    enforce-whitelist=false
    resource-pack-sha1=
    spawn-protection=16
    max-world-size=29999984

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 25565

  annotations: {}

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: spigot.minecraft.test
      paths:
        - /
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

persistentVolume:
  storage: 10Gi
  accessModes:
    - ReadWriteOnce

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

extraVolumeMounts: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
