# Default values for minecraft-bungee.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

image:
  repository: quay.io/kamaradcoal/minecraft-bungee
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

extraEnv:
  - name: JAR_ARGS
    value: -Xmx512M -Xms256M

kamarad:
  serverId: "1"

bungee:
  config: |
    prevent_proxy_connections: false
    listeners:
      - query_port: 25577
        motd: Proxy MOTD
        tab_list: GLOBAL_PING
        query_enabled: true
        proxy_protocol: true
        forced_hosts: []
        priorities: []
        ping_passthrough: false
        bind_local_address: true
        host: "0.0.0.0:25577"
        max_players: -1
        tab_size: 60
        force_default_server: true
    remote_ping_cache: -1
    network_compression_threshold: 256
    permissions:
      default:
        - bungeecord.command.server
        - bungeecord.command.list
      admin:
        - bungeecord.command.alert
        - bungeecord.command.end
        - bungeecord.command.ip
        - bungeecord.command.reload
    log_pings: false
    connection_throttle_limit: 3
    server_connect_timeout: 5000
    timeout: 30000
    player_limit: -1
    ip_forward: true
    groups: {}
    remote_ping_timeout: 5000
    connection_throttle: 4000
    log_commands: false
    stats: uuid_replace_here
    online_mode: true
    forge_support: false
    disabled_commands:
      - disabledcommandhere
    servers: []

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: LoadBalancer
  port: 25577

  annotations:
    external-dns.alpha.kubernetes.io/hostname: "bungee.minecraft.test"
    external-dns.alpha.kubernetes.io/ttl: "60"

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: bungee.minecraft.test
      paths:
        - /
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

persistentVolume:
  storage: 10Gi
  accessModes:
    - ReadWriteOnce

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

extraVolumeMounts: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
