apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "minecraft-spigot.fullname" . }}
  labels:
    {{- include "minecraft-spigot.labels" . | nindent 4 }}
    coal.kamarad.app/server-id: "{{ .Values.kamarad.serverId }}"
    coal.kamarad.app/game: "minecraft"
    coal.kamarad.app/minecraft-distro: "spigot"
spec:
  resources:
    requests:
      storage: {{ .Values.persistentVolume.storage }}
  {{- with .Values.persistentVolume.accessModes }}
  accessModes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
