{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "minecraft-bungee.serviceAccountName" . }}
  labels:
    {{- include "minecraft-bungee.labels" . | nindent 4 }}
    coal.kamarad.app/server-id: "{{ .Values.kamarad.serverId }}"
    coal.kamarad.app/game: "minecraft"
    coal.kamarad.app/minecraft-distro: "bungee"
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
